// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjR6f66Z5NGwOlrMmuuKUsm1IfHgenLvs',
    appId: '1:644703712:web:737bc2fefbf57e20223785',
    messagingSenderId: '644703712',
    projectId: 'coffeeshop-fb0c6',
    authDomain: 'coffeeshop-fb0c6.firebaseapp.com',
    storageBucket: 'coffeeshop-fb0c6.firebasestorage.app',
    measurementId: 'G-KVLBKKM2DZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt_VXsyeXdYHulNo33TFxVQdVkcze_els',
    appId: '1:644703712:android:17656fa6a32b2a04223785',
    messagingSenderId: '644703712',
    projectId: 'coffeeshop-fb0c6',
    storageBucket: 'coffeeshop-fb0c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMq_K547kyBZ6smiFpAP8zbQ03RqRCXzw',
    appId: '1:644703712:ios:30ba447867c01abc223785',
    messagingSenderId: '644703712',
    projectId: 'coffeeshop-fb0c6',
    storageBucket: 'coffeeshop-fb0c6.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMq_K547kyBZ6smiFpAP8zbQ03RqRCXzw',
    appId: '1:644703712:ios:30ba447867c01abc223785',
    messagingSenderId: '644703712',
    projectId: 'coffeeshop-fb0c6',
    storageBucket: 'coffeeshop-fb0c6.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjR6f66Z5NGwOlrMmuuKUsm1IfHgenLvs',
    appId: '1:644703712:web:f0113736821d1c2e223785',
    messagingSenderId: '644703712',
    projectId: 'coffeeshop-fb0c6',
    authDomain: 'coffeeshop-fb0c6.firebaseapp.com',
    storageBucket: 'coffeeshop-fb0c6.firebasestorage.app',
    measurementId: 'G-NNESZRS4ZW',
  );
}
